// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/amadeus/func/amadeus.func.proto

package amadeus_func

import (
	_type "api/amadeus/type"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// msgCode: 0001
// => amadeus.type.FlightOffersResult (0050)
// => amadeus.comn.BadRequest (0950)
type FlightLowFareSearchRequest struct {
	Origin               string   `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	DepartureDate        string   `protobuf:"bytes,3,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"`
	ReturnDate           string   `protobuf:"bytes,4,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlightLowFareSearchRequest) Reset()         { *m = FlightLowFareSearchRequest{} }
func (m *FlightLowFareSearchRequest) String() string { return proto.CompactTextString(m) }
func (*FlightLowFareSearchRequest) ProtoMessage()    {}
func (*FlightLowFareSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c2e715053c5104c, []int{0}
}

func (m *FlightLowFareSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlightLowFareSearchRequest.Unmarshal(m, b)
}
func (m *FlightLowFareSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlightLowFareSearchRequest.Marshal(b, m, deterministic)
}
func (m *FlightLowFareSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlightLowFareSearchRequest.Merge(m, src)
}
func (m *FlightLowFareSearchRequest) XXX_Size() int {
	return xxx_messageInfo_FlightLowFareSearchRequest.Size(m)
}
func (m *FlightLowFareSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FlightLowFareSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FlightLowFareSearchRequest proto.InternalMessageInfo

func (m *FlightLowFareSearchRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *FlightLowFareSearchRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *FlightLowFareSearchRequest) GetDepartureDate() string {
	if m != nil {
		return m.DepartureDate
	}
	return ""
}

func (m *FlightLowFareSearchRequest) GetReturnDate() string {
	if m != nil {
		return m.ReturnDate
	}
	return ""
}

func init() {
	proto.RegisterType((*FlightLowFareSearchRequest)(nil), "amadeus.func.FlightLowFareSearchRequest")
}

func init() {
	proto.RegisterFile("api/amadeus/func/amadeus.func.proto", fileDescriptor_1c2e715053c5104c)
}

var fileDescriptor_1c2e715053c5104c = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x59, 0x95, 0x82, 0x53, 0xed, 0x21, 0x82, 0x2c, 0x7b, 0xb1, 0x28, 0x62, 0x4f, 0x29,
	0xe8, 0x13, 0x08, 0xd2, 0x93, 0xa7, 0xf6, 0x01, 0x64, 0xdc, 0x8c, 0xdd, 0x40, 0x4d, 0xe2, 0x64,
	0xa2, 0xe8, 0xc3, 0xf8, 0xac, 0xb2, 0x89, 0x96, 0x2e, 0xd4, 0xe3, 0xff, 0xe5, 0xfb, 0x61, 0xf2,
	0xc3, 0x15, 0x06, 0x3b, 0xc7, 0x57, 0x34, 0x94, 0xe2, 0xfc, 0x25, 0xb9, 0xf6, 0x2f, 0xe8, 0x3e,
	0xe8, 0xc0, 0x5e, 0xbc, 0x3a, 0xd9, 0x65, 0xcd, 0xa0, 0x22, 0x9f, 0x81, 0xb6, 0x95, 0x3e, 0x94,
	0xca, 0xe5, 0x77, 0x05, 0xcd, 0x62, 0x63, 0xd7, 0x9d, 0x3c, 0xfa, 0x8f, 0x05, 0x32, 0xad, 0x08,
	0xb9, 0xed, 0x96, 0xf4, 0x96, 0x28, 0x8a, 0x3a, 0x87, 0x91, 0x67, 0xbb, 0xb6, 0xae, 0xae, 0xa6,
	0xd5, 0xec, 0x78, 0xf9, 0x9b, 0xd4, 0x14, 0xc6, 0x86, 0xa2, 0x58, 0x87, 0x62, 0xbd, 0xab, 0x0f,
	0xf2, 0xe3, 0x2e, 0x52, 0xd7, 0x30, 0x31, 0x14, 0x90, 0x25, 0x31, 0x3d, 0x19, 0x14, 0xaa, 0x0f,
	0xb3, 0x74, 0xba, 0xa5, 0x0f, 0x28, 0xa4, 0x2e, 0x60, 0xcc, 0x24, 0x89, 0x5d, 0x71, 0x8e, 0xb2,
	0x03, 0x05, 0xf5, 0xc2, 0xed, 0x17, 0x4c, 0xee, 0xcb, 0xd9, 0x2b, 0xe2, 0x77, 0xdb, 0x92, 0xea,
	0xe0, 0x6c, 0xcf, 0xc5, 0x6a, 0xa6, 0x07, 0x8b, 0xfc, 0xff, 0xa9, 0xe6, 0x46, 0x0f, 0x86, 0xd8,
	0x6b, 0xc6, 0xb4, 0x91, 0xe7, 0x51, 0xde, 0xe8, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x0b,
	0x4e, 0x19, 0x7d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AmadeusServiceClient is the client API for AmadeusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AmadeusServiceClient interface {
	// I know where I want to fly, the dates and duration, what are the best flight deals?
	FlightLowFareSearch(ctx context.Context, in *FlightLowFareSearchRequest, opts ...grpc.CallOption) (*_type.FlightLowFareSearchResult, error)
}

type amadeusServiceClient struct {
	cc *grpc.ClientConn
}

func NewAmadeusServiceClient(cc *grpc.ClientConn) AmadeusServiceClient {
	return &amadeusServiceClient{cc}
}

func (c *amadeusServiceClient) FlightLowFareSearch(ctx context.Context, in *FlightLowFareSearchRequest, opts ...grpc.CallOption) (*_type.FlightLowFareSearchResult, error) {
	out := new(_type.FlightLowFareSearchResult)
	err := c.cc.Invoke(ctx, "/amadeus.func.AmadeusService/FlightLowFareSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AmadeusServiceServer is the server API for AmadeusService service.
type AmadeusServiceServer interface {
	// I know where I want to fly, the dates and duration, what are the best flight deals?
	FlightLowFareSearch(context.Context, *FlightLowFareSearchRequest) (*_type.FlightLowFareSearchResult, error)
}

func RegisterAmadeusServiceServer(s *grpc.Server, srv AmadeusServiceServer) {
	s.RegisterService(&_AmadeusService_serviceDesc, srv)
}

func _AmadeusService_FlightLowFareSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightLowFareSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmadeusServiceServer).FlightLowFareSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/amadeus.func.AmadeusService/FlightLowFareSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmadeusServiceServer).FlightLowFareSearch(ctx, req.(*FlightLowFareSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AmadeusService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "amadeus.func.AmadeusService",
	HandlerType: (*AmadeusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FlightLowFareSearch",
			Handler:    _AmadeusService_FlightLowFareSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/amadeus/func/amadeus.func.proto",
}
