// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/amadeus/type/amadeus.type.proto

package amadeus_type

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// msgCode: 0050
type FlightLowFareSearchResult struct {
	Type                 string       `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string       `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	OfferItems           []*OfferItem `protobuf:"bytes,3,rep,name=offerItems,proto3" json:"offerItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FlightLowFareSearchResult) Reset()         { *m = FlightLowFareSearchResult{} }
func (m *FlightLowFareSearchResult) String() string { return proto.CompactTextString(m) }
func (*FlightLowFareSearchResult) ProtoMessage()    {}
func (*FlightLowFareSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_04767f1e5698113a, []int{0}
}

func (m *FlightLowFareSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlightLowFareSearchResult.Unmarshal(m, b)
}
func (m *FlightLowFareSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlightLowFareSearchResult.Marshal(b, m, deterministic)
}
func (m *FlightLowFareSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlightLowFareSearchResult.Merge(m, src)
}
func (m *FlightLowFareSearchResult) XXX_Size() int {
	return xxx_messageInfo_FlightLowFareSearchResult.Size(m)
}
func (m *FlightLowFareSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FlightLowFareSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_FlightLowFareSearchResult proto.InternalMessageInfo

func (m *FlightLowFareSearchResult) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FlightLowFareSearchResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FlightLowFareSearchResult) GetOfferItems() []*OfferItem {
	if m != nil {
		return m.OfferItems
	}
	return nil
}

// msgCode: 0051
type OfferItem struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Price                *Price     `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	PricePerAdult        *Price     `protobuf:"bytes,3,opt,name=pricePerAdult,proto3" json:"pricePerAdult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OfferItem) Reset()         { *m = OfferItem{} }
func (m *OfferItem) String() string { return proto.CompactTextString(m) }
func (*OfferItem) ProtoMessage()    {}
func (*OfferItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_04767f1e5698113a, []int{1}
}

func (m *OfferItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferItem.Unmarshal(m, b)
}
func (m *OfferItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferItem.Marshal(b, m, deterministic)
}
func (m *OfferItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferItem.Merge(m, src)
}
func (m *OfferItem) XXX_Size() int {
	return xxx_messageInfo_OfferItem.Size(m)
}
func (m *OfferItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferItem.DiscardUnknown(m)
}

var xxx_messageInfo_OfferItem proto.InternalMessageInfo

func (m *OfferItem) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *OfferItem) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *OfferItem) GetPricePerAdult() *Price {
	if m != nil {
		return m.PricePerAdult
	}
	return nil
}

// msgCode: 0052
type Service struct {
	Segments             []*Segment `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_04767f1e5698113a, []int{2}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetSegments() []*Segment {
	if m != nil {
		return m.Segments
	}
	return nil
}

// msgCode: 0053
type Segment struct {
	FlightSegments        []*FlightSegment       `protobuf:"bytes,1,rep,name=flightSegments,proto3" json:"flightSegments,omitempty"`
	PricingDetailPerAdult *PricingDetailPerAdult `protobuf:"bytes,2,opt,name=pricingDetailPerAdult,proto3" json:"pricingDetailPerAdult,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *Segment) Reset()         { *m = Segment{} }
func (m *Segment) String() string { return proto.CompactTextString(m) }
func (*Segment) ProtoMessage()    {}
func (*Segment) Descriptor() ([]byte, []int) {
	return fileDescriptor_04767f1e5698113a, []int{3}
}

func (m *Segment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Segment.Unmarshal(m, b)
}
func (m *Segment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Segment.Marshal(b, m, deterministic)
}
func (m *Segment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Segment.Merge(m, src)
}
func (m *Segment) XXX_Size() int {
	return xxx_messageInfo_Segment.Size(m)
}
func (m *Segment) XXX_DiscardUnknown() {
	xxx_messageInfo_Segment.DiscardUnknown(m)
}

var xxx_messageInfo_Segment proto.InternalMessageInfo

func (m *Segment) GetFlightSegments() []*FlightSegment {
	if m != nil {
		return m.FlightSegments
	}
	return nil
}

func (m *Segment) GetPricingDetailPerAdult() *PricingDetailPerAdult {
	if m != nil {
		return m.PricingDetailPerAdult
	}
	return nil
}

// msgCode: 0054
type FlightSegment struct {
	Departure            *DepartureArrival `protobuf:"bytes,1,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival              *DepartureArrival `protobuf:"bytes,2,opt,name=arrival,proto3" json:"arrival,omitempty"`
	CarrierCode          string            `protobuf:"bytes,3,opt,name=carrierCode,proto3" json:"carrierCode,omitempty"`
	Number               string            `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	Aircraft             *Aircraft         `protobuf:"bytes,5,opt,name=aircraft,proto3" json:"aircraft,omitempty"`
	Operating            *Operating        `protobuf:"bytes,6,opt,name=operating,proto3" json:"operating,omitempty"`
	Duration             string            `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FlightSegment) Reset()         { *m = FlightSegment{} }
func (m *FlightSegment) String() string { return proto.CompactTextString(m) }
func (*FlightSegment) ProtoMessage()    {}
func (*FlightSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_04767f1e5698113a, []int{4}
}

func (m *FlightSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlightSegment.Unmarshal(m, b)
}
func (m *FlightSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlightSegment.Marshal(b, m, deterministic)
}
func (m *FlightSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlightSegment.Merge(m, src)
}
func (m *FlightSegment) XXX_Size() int {
	return xxx_messageInfo_FlightSegment.Size(m)
}
func (m *FlightSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_FlightSegment.DiscardUnknown(m)
}

var xxx_messageInfo_FlightSegment proto.InternalMessageInfo

func (m *FlightSegment) GetDeparture() *DepartureArrival {
	if m != nil {
		return m.Departure
	}
	return nil
}

func (m *FlightSegment) GetArrival() *DepartureArrival {
	if m != nil {
		return m.Arrival
	}
	return nil
}

func (m *FlightSegment) GetCarrierCode() string {
	if m != nil {
		return m.CarrierCode
	}
	return ""
}

func (m *FlightSegment) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *FlightSegment) GetAircraft() *Aircraft {
	if m != nil {
		return m.Aircraft
	}
	return nil
}

func (m *FlightSegment) GetOperating() *Operating {
	if m != nil {
		return m.Operating
	}
	return nil
}

func (m *FlightSegment) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

// msgCode: 0055
type DepartureArrival struct {
	IataCode             string   `protobuf:"bytes,1,opt,name=iataCode,proto3" json:"iataCode,omitempty"`
	Terminal             string   `protobuf:"bytes,2,opt,name=terminal,proto3" json:"terminal,omitempty"`
	At                   string   `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepartureArrival) Reset()         { *m = DepartureArrival{} }
func (m *DepartureArrival) String() string { return proto.CompactTextString(m) }
func (*DepartureArrival) ProtoMessage()    {}
func (*DepartureArrival) Descriptor() ([]byte, []int) {
	return fileDescriptor_04767f1e5698113a, []int{5}
}

func (m *DepartureArrival) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartureArrival.Unmarshal(m, b)
}
func (m *DepartureArrival) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartureArrival.Marshal(b, m, deterministic)
}
func (m *DepartureArrival) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartureArrival.Merge(m, src)
}
func (m *DepartureArrival) XXX_Size() int {
	return xxx_messageInfo_DepartureArrival.Size(m)
}
func (m *DepartureArrival) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartureArrival.DiscardUnknown(m)
}

var xxx_messageInfo_DepartureArrival proto.InternalMessageInfo

func (m *DepartureArrival) GetIataCode() string {
	if m != nil {
		return m.IataCode
	}
	return ""
}

func (m *DepartureArrival) GetTerminal() string {
	if m != nil {
		return m.Terminal
	}
	return ""
}

func (m *DepartureArrival) GetAt() string {
	if m != nil {
		return m.At
	}
	return ""
}

// msgCode: 0056
type Aircraft struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Aircraft) Reset()         { *m = Aircraft{} }
func (m *Aircraft) String() string { return proto.CompactTextString(m) }
func (*Aircraft) ProtoMessage()    {}
func (*Aircraft) Descriptor() ([]byte, []int) {
	return fileDescriptor_04767f1e5698113a, []int{6}
}

func (m *Aircraft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Aircraft.Unmarshal(m, b)
}
func (m *Aircraft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Aircraft.Marshal(b, m, deterministic)
}
func (m *Aircraft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Aircraft.Merge(m, src)
}
func (m *Aircraft) XXX_Size() int {
	return xxx_messageInfo_Aircraft.Size(m)
}
func (m *Aircraft) XXX_DiscardUnknown() {
	xxx_messageInfo_Aircraft.DiscardUnknown(m)
}

var xxx_messageInfo_Aircraft proto.InternalMessageInfo

func (m *Aircraft) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// msgCode: 0057
type Operating struct {
	CarrierCode          string   `protobuf:"bytes,3,opt,name=carrierCode,proto3" json:"carrierCode,omitempty"`
	Number               string   `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operating) Reset()         { *m = Operating{} }
func (m *Operating) String() string { return proto.CompactTextString(m) }
func (*Operating) ProtoMessage()    {}
func (*Operating) Descriptor() ([]byte, []int) {
	return fileDescriptor_04767f1e5698113a, []int{7}
}

func (m *Operating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operating.Unmarshal(m, b)
}
func (m *Operating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operating.Marshal(b, m, deterministic)
}
func (m *Operating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operating.Merge(m, src)
}
func (m *Operating) XXX_Size() int {
	return xxx_messageInfo_Operating.Size(m)
}
func (m *Operating) XXX_DiscardUnknown() {
	xxx_messageInfo_Operating.DiscardUnknown(m)
}

var xxx_messageInfo_Operating proto.InternalMessageInfo

func (m *Operating) GetCarrierCode() string {
	if m != nil {
		return m.CarrierCode
	}
	return ""
}

func (m *Operating) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

// msgCode: 0058
type PricingDetailPerAdult struct {
	TravelClass          string   `protobuf:"bytes,1,opt,name=travelClass,proto3" json:"travelClass,omitempty"`
	FareClass            string   `protobuf:"bytes,2,opt,name=fareClass,proto3" json:"fareClass,omitempty"`
	Availability         int32    `protobuf:"varint,3,opt,name=availability,proto3" json:"availability,omitempty"`
	FareBasis            string   `protobuf:"bytes,4,opt,name=fareBasis,proto3" json:"fareBasis,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PricingDetailPerAdult) Reset()         { *m = PricingDetailPerAdult{} }
func (m *PricingDetailPerAdult) String() string { return proto.CompactTextString(m) }
func (*PricingDetailPerAdult) ProtoMessage()    {}
func (*PricingDetailPerAdult) Descriptor() ([]byte, []int) {
	return fileDescriptor_04767f1e5698113a, []int{8}
}

func (m *PricingDetailPerAdult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PricingDetailPerAdult.Unmarshal(m, b)
}
func (m *PricingDetailPerAdult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PricingDetailPerAdult.Marshal(b, m, deterministic)
}
func (m *PricingDetailPerAdult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricingDetailPerAdult.Merge(m, src)
}
func (m *PricingDetailPerAdult) XXX_Size() int {
	return xxx_messageInfo_PricingDetailPerAdult.Size(m)
}
func (m *PricingDetailPerAdult) XXX_DiscardUnknown() {
	xxx_messageInfo_PricingDetailPerAdult.DiscardUnknown(m)
}

var xxx_messageInfo_PricingDetailPerAdult proto.InternalMessageInfo

func (m *PricingDetailPerAdult) GetTravelClass() string {
	if m != nil {
		return m.TravelClass
	}
	return ""
}

func (m *PricingDetailPerAdult) GetFareClass() string {
	if m != nil {
		return m.FareClass
	}
	return ""
}

func (m *PricingDetailPerAdult) GetAvailability() int32 {
	if m != nil {
		return m.Availability
	}
	return 0
}

func (m *PricingDetailPerAdult) GetFareBasis() string {
	if m != nil {
		return m.FareBasis
	}
	return ""
}

// msgCode: 0059
type Price struct {
	Total                string   `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	TotalTaxes           string   `protobuf:"bytes,2,opt,name=totalTaxes,proto3" json:"totalTaxes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_04767f1e5698113a, []int{9}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

func (m *Price) GetTotalTaxes() string {
	if m != nil {
		return m.TotalTaxes
	}
	return ""
}

func init() {
	proto.RegisterType((*FlightLowFareSearchResult)(nil), "amadeus.type.FlightLowFareSearchResult")
	proto.RegisterType((*OfferItem)(nil), "amadeus.type.OfferItem")
	proto.RegisterType((*Service)(nil), "amadeus.type.Service")
	proto.RegisterType((*Segment)(nil), "amadeus.type.Segment")
	proto.RegisterType((*FlightSegment)(nil), "amadeus.type.FlightSegment")
	proto.RegisterType((*DepartureArrival)(nil), "amadeus.type.DepartureArrival")
	proto.RegisterType((*Aircraft)(nil), "amadeus.type.Aircraft")
	proto.RegisterType((*Operating)(nil), "amadeus.type.Operating")
	proto.RegisterType((*PricingDetailPerAdult)(nil), "amadeus.type.PricingDetailPerAdult")
	proto.RegisterType((*Price)(nil), "amadeus.type.Price")
}

func init() {
	proto.RegisterFile("api/amadeus/type/amadeus.type.proto", fileDescriptor_04767f1e5698113a)
}

var fileDescriptor_04767f1e5698113a = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xd3, 0xa6, 0x8d, 0x27, 0x6d, 0x85, 0x16, 0x52, 0xcc, 0x87, 0xa2, 0x68, 0x7b, 0x29,
	0x97, 0x54, 0x04, 0x21, 0x40, 0x2a, 0x87, 0x90, 0x12, 0x09, 0x09, 0x89, 0x6a, 0xc3, 0x05, 0x6e,
	0x13, 0x7b, 0x92, 0xae, 0xe4, 0xd8, 0xd6, 0x7a, 0x1d, 0xda, 0x9f, 0xc2, 0x9d, 0x0b, 0xff, 0x84,
	0x9f, 0x85, 0x76, 0xfd, 0x11, 0x3b, 0x6d, 0x85, 0xc4, 0x6d, 0xe6, 0xbd, 0x37, 0x33, 0x6f, 0x26,
	0xde, 0xc0, 0x09, 0x26, 0xf2, 0x0c, 0x57, 0x18, 0x50, 0x96, 0x9e, 0xe9, 0x9b, 0x84, 0xca, 0x64,
	0x68, 0x92, 0x61, 0xa2, 0x62, 0x1d, 0xb3, 0x83, 0x3a, 0xc6, 0xaf, 0xe1, 0xc9, 0x34, 0x94, 0xcb,
	0x2b, 0xfd, 0x39, 0xfe, 0x31, 0x45, 0x45, 0x33, 0x42, 0xe5, 0x5f, 0x09, 0x4a, 0xb3, 0x50, 0x33,
	0x06, 0xbb, 0x46, 0xe4, 0x39, 0x03, 0xe7, 0xd4, 0x15, 0x36, 0x66, 0x47, 0xd0, 0x92, 0x81, 0xd7,
	0xb2, 0x48, 0x4b, 0x06, 0xec, 0x0d, 0x40, 0xbc, 0x58, 0x90, 0xfa, 0xa4, 0x69, 0x95, 0x7a, 0x3b,
	0x83, 0x9d, 0xd3, 0xee, 0xe8, 0xf1, 0xb0, 0x31, 0xf7, 0x4b, 0xc9, 0x8b, 0x9a, 0x94, 0xff, 0x72,
	0xc0, 0xad, 0x18, 0xf6, 0x12, 0x3a, 0x29, 0xa9, 0xb5, 0xf4, 0x29, 0xf5, 0x1c, 0xdb, 0xa4, 0xd7,
	0x6c, 0x32, 0xcb, 0x59, 0x51, 0xc9, 0xd8, 0x0b, 0x68, 0x27, 0x4a, 0xfa, 0x64, 0xcd, 0x74, 0x47,
	0x0f, 0x9b, 0xfa, 0x4b, 0x43, 0x89, 0x5c, 0xc1, 0xde, 0xc1, 0xa1, 0x0d, 0x2e, 0x49, 0x8d, 0x83,
	0x2c, 0xd4, 0xde, 0xce, 0xfd, 0x25, 0x4d, 0x25, 0x3f, 0x87, 0xfd, 0x62, 0x74, 0xee, 0x71, 0xb9,
	0xa2, 0x48, 0xdf, 0xeb, 0xd1, 0xb2, 0xa2, 0x92, 0xf1, 0xdf, 0x8e, 0x29, 0xb7, 0x09, 0x9b, 0xc0,
	0xd1, 0xc2, 0x9e, 0x7a, 0xd6, 0x6c, 0xf2, 0xac, 0xd9, 0x64, 0x5a, 0xd7, 0x88, 0xad, 0x12, 0xf6,
	0x0d, 0x7a, 0xc6, 0x9f, 0x8c, 0x96, 0x17, 0xa4, 0x51, 0x86, 0xd5, 0x46, 0xf9, 0x11, 0x4e, 0x6e,
	0x6f, 0x74, 0x4b, 0x2a, 0xee, 0xee, 0xc0, 0xff, 0xb4, 0xe0, 0xb0, 0x31, 0x9c, 0x9d, 0x83, 0x1b,
	0x50, 0x82, 0x4a, 0x67, 0x2a, 0xff, 0x08, 0xba, 0xa3, 0x7e, 0x73, 0xc0, 0x45, 0x49, 0x8f, 0x95,
	0x92, 0x6b, 0x0c, 0xc5, 0xa6, 0x80, 0xbd, 0x85, 0x7d, 0xcc, 0xd1, 0xc2, 0xdc, 0xbf, 0x6a, 0x4b,
	0x39, 0x1b, 0x40, 0xd7, 0x37, 0x31, 0xa9, 0x49, 0x1c, 0x90, 0xfd, 0xb1, 0x5c, 0x51, 0x87, 0xd8,
	0x31, 0xec, 0x45, 0xd9, 0x6a, 0x4e, 0xca, 0xdb, 0xb5, 0x64, 0x91, 0xb1, 0x11, 0x74, 0x50, 0x2a,
	0x5f, 0xe1, 0x42, 0x7b, 0x6d, 0x3b, 0xf4, 0xb8, 0x39, 0x74, 0x5c, 0xb0, 0xa2, 0xd2, 0xb1, 0xd7,
	0xe0, 0xc6, 0x09, 0x29, 0xd4, 0x32, 0x5a, 0x7a, 0x7b, 0xb6, 0x68, 0xfb, 0x03, 0x2e, 0x69, 0xb1,
	0x51, 0xb2, 0xa7, 0xd0, 0x09, 0x32, 0x13, 0xc7, 0x91, 0xb7, 0x6f, 0x4d, 0x54, 0x39, 0xff, 0x0e,
	0x0f, 0xb6, 0xb7, 0x33, 0x7a, 0x89, 0x1a, 0xed, 0x46, 0xf9, 0x83, 0xaa, 0x72, 0xc3, 0x69, 0x52,
	0x2b, 0x19, 0x15, 0xb7, 0x72, 0x45, 0x95, 0x9b, 0x07, 0x87, 0xba, 0xb8, 0x41, 0x0b, 0x35, 0xef,
	0x43, 0xa7, 0x5c, 0xc2, 0x3c, 0x50, 0x7f, 0xd3, 0xcf, 0xc6, 0xfc, 0x23, 0xb8, 0x95, 0xdf, 0xff,
	0xbf, 0x24, 0xff, 0xe9, 0x40, 0xef, 0xce, 0xcf, 0xc7, 0xf4, 0xd4, 0x0a, 0xd7, 0x14, 0x4e, 0x42,
	0x4c, 0xd3, 0x62, 0x76, 0x1d, 0x62, 0xcf, 0xc1, 0x5d, 0xa0, 0xa2, 0x9c, 0xcf, 0xf7, 0xd9, 0x00,
	0x8c, 0xc3, 0x01, 0xae, 0x51, 0x86, 0x38, 0x97, 0xa1, 0xd4, 0x37, 0xd6, 0x54, 0x5b, 0x34, 0xb0,
	0xb2, 0xc3, 0x07, 0x4c, 0x65, 0x5a, 0x18, 0xdb, 0x00, 0xfc, 0x3d, 0xb4, 0xed, 0x5b, 0x65, 0x8f,
	0xa0, 0xad, 0x63, 0x8d, 0x61, 0x61, 0x22, 0x4f, 0x58, 0x1f, 0xc0, 0x06, 0x5f, 0xf1, 0x9a, 0xca,
	0xf9, 0x35, 0x64, 0xbe, 0x67, 0xff, 0x08, 0x5f, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x45,
	0xb1, 0x9e, 0x2f, 0x05, 0x00, 0x00,
}
