// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/amadeus/amadeus.proto

package go_kit_srv_amadeus

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_38f8fabff549dd84, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_38f8fabff549dd84, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.kit.srv.amadeus.Request")
	proto.RegisterType((*Response)(nil), "go.kit.srv.amadeus.Response")
}

func init() { proto.RegisterFile("pb/amadeus/amadeus.proto", fileDescriptor_38f8fabff549dd84) }

var fileDescriptor_38f8fabff549dd84 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x48, 0xd2, 0x4f,
	0xcc, 0x4d, 0x4c, 0x49, 0x2d, 0x2d, 0x86, 0xd1, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x42,
	0xe9, 0xf9, 0x7a, 0xd9, 0x99, 0x25, 0x7a, 0xc5, 0x45, 0x65, 0x7a, 0x50, 0x19, 0x25, 0x59, 0x2e,
	0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49, 0x85, 0x8b, 0x23, 0x28, 0xb5, 0xb8,
	0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x82, 0x8b, 0x3d, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x1d, 0xa6,
	0x04, 0xc6, 0x35, 0x0a, 0xe3, 0xe2, 0x73, 0x84, 0x98, 0x17, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c,
	0x2a, 0xe4, 0xc2, 0xc5, 0xee, 0x5e, 0x94, 0x9a, 0x5a, 0x92, 0x5a, 0x24, 0x24, 0xad, 0x87, 0x69,
	0xad, 0x1e, 0xd4, 0x4e, 0x29, 0x19, 0xec, 0x92, 0x10, 0x1b, 0x93, 0xd8, 0xc0, 0xee, 0x36, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x43, 0xf8, 0xf5, 0x23, 0xd3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AmadeusServiceClient is the client API for AmadeusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AmadeusServiceClient interface {
	Greeter(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type amadeusServiceClient struct {
	cc *grpc.ClientConn
}

func NewAmadeusServiceClient(cc *grpc.ClientConn) AmadeusServiceClient {
	return &amadeusServiceClient{cc}
}

func (c *amadeusServiceClient) Greeter(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.kit.srv.amadeus.AmadeusService/Greeter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AmadeusServiceServer is the server API for AmadeusService service.
type AmadeusServiceServer interface {
	Greeter(context.Context, *Request) (*Response, error)
}

func RegisterAmadeusServiceServer(s *grpc.Server, srv AmadeusServiceServer) {
	s.RegisterService(&_AmadeusService_serviceDesc, srv)
}

func _AmadeusService_Greeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmadeusServiceServer).Greeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.kit.srv.amadeus.AmadeusService/Greeter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmadeusServiceServer).Greeter(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _AmadeusService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.kit.srv.amadeus.AmadeusService",
	HandlerType: (*AmadeusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeter",
			Handler:    _AmadeusService_Greeter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/amadeus/amadeus.proto",
}
